apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ .Release.Name }}-postgres-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: "postgres"
data:
  POSTGRES_DB: "house"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "12345"