apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
    role: web
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: gunicorn
      nodePort: {{ .Values.service.nodePort }}