apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: postgres
data:
  POSTGRES_DB: house
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: "12345"
  POSTGRES_URL: postgres-service