apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 32080
      protocol: TCP