apiVersion: v1
kind: Service
metadata:
  name: python-demo-app-web
  namespace: cloud
spec:
  selector:
    app: python-demo-app
    role: web
  ports:
    - name: http
      port: 80
      targetPort: gunicorn