job:
  repository: manojmanivannan18/flaskedge
  tag: master
  command:
    - python3
  args:
    - cli.py
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m