web:
  replicas: 2
  image: ghcr.io/manojmanivannan/k8sessentials
  tag: latest
  args:
    - '--bind'
    - '0.0.0.0'
    - 'app:app'
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

job:
  image: ghcr.io/manojmanivannan/k8sessentials
  tag: latest
  command:
    - python3
  args:
    - cli.py
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

ingress:
  rules:
    - host: python-app.demo.com
    # - host: second-host-python-app.demo.com

service:
  port: 80
  nodePort: 30080